apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: {{ .Release.Namespace }}
  labels:
    app: cart
spec:
  ports:
  - port: 80
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: cart
---
