apiVersion: v1
kind: Service
metadata:
  name: cartdb
  namespace: {{ .Release.Namespace }}
  labels:
    app: cartdb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: cartdb
---
