apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: {{ .Release.Namespace }}
  labels:
    app: catalog
spec:
  ports:
  - port: 80
    targetPort: 5002
    protocol: TCP
    name: http
  selector:
    app: catalog
---
