apiVersion: v1
kind: Service
metadata:
  name: idp
  namespace: {{ .Release.Namespace }}
  labels:
    app: idp
spec:
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: idp
---
