apiVersion: v1
kind: Service
metadata:
  name: rating
  namespace: {{ .Release.Namespace }}
  labels:
    app: rating
spec:
  ports:
  - port: 80
    targetPort: 5007
    protocol: TCP
    name: http
  selector:
    app: rating
---
