apiVersion: v1
kind: Service
metadata:
  name: review
  namespace: {{ .Release.Namespace }}
  labels:
    app: review
spec:
  ports:
  - port: 80
    targetPort: 5006
    protocol: TCP
    name: http
  selector:
    app: review
---
