apiVersion: v1
kind: Service
metadata:
  name: reviewdb
  namespace: {{ .Release.Namespace }}
  labels:
    app: reviewdb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: reviewdb
---
