apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spa-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spa
        version: v1
    spec:
      containers:
      - name: spa
        image: {{.Values.image.imageRegistry}}/cs-spa:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: "WEB_HOST_ALIAS"
          value: {{ .Values.hosts.web }}
        - name: "API_HOST_ALIAS"
          value: {{ .Values.hosts.api }}
        - name: "ID_HOST_ALIAS"
          value: {{ .Values.hosts.idp }}
        - name: "GATEWAY_IP"
          value: {{ .Values.gateway.ip }}
        ports:
        - containerPort: 8080
---