apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcheck-config
#common configuration shared between all applications
data:
  appsettings.json: |-
    {
      "MySql": {
        "ConnectionString": {{.Values.MySql.ConnectionString | quote}}
      },
      "UrlsCheck": {{.Values.UrlsCheck | quote}}
    }