apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kikker-edsn-callproxy
spec:
  hosts:
  - "*"
  gateways:
  - kikker-gateway-vncluster
  http:
  - match:
    - uri:
        prefix: /edsn
    route:
    - destination:
        host: edsn-client-usage-sample
        port:
          number: 80