AppSettings:
  SiteTitle: Kikker
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information

eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
mysql:
  client:
    server: localhost
    sslmode: none
redis:
  client:
    host: localhost
logstash:
  uri: http://localhost:8080
audience:
  secret: Y2F0Y2hlciUyMHdvbmclMjBsb3ZlJTIwLm5ldA==
  iss: http://www.c-sharpcorner.com/members/catcher-wong
  aud: Infodation