AppSettings:
  SiteTitle: Kikker
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information
#eureka:
  #instance:
    #homePageUrl: http://eureka:8761
  #client:
    #serviceUrl: http://eureka:8761/eureka/
mysql:
  client:
    server: mysql
    sslmode: none
redis:
  client:
    host: localhost
logstash:
  uri: http://logstash:8080
audience:
  secret: my-secret-token-to-change-in-production
  iss: http://www.c-sharpcorner.com/members/catcher-wong
  aud: Infodation