#machinename: eureka
#eureka:
  #client:
    #shouldFetchRegistry: true
    #validateCertificates: false
  #instance:
    #port: 5002
mysql:
  connectionString: Server=mysql;Database=kikker;Uid=user;Pwd=123;