FROM microsoft/aspnetcore-build:2.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["src/Ratings/Ratings.csproj", "src/Ratings/"]

RUN dotnet restore "src/Ratings/Ratings.csproj"
COPY . .
WORKDIR "/src/src/Ratings"
RUN dotnet build --no-restore "Ratings.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]