service:
  type: NodePort
  nodePort: 30899
podAnnotations:
  sidecar.istio.io/inject: "false"
rootUser:
  password: root12!@
db:
  user: auth
  password: auth12!@
  name: kikkerauth
replication:
  enabled: false
nodeSelector:
  pv: "true"