version: '3.0'

services:

  config-server:
    image: "steeltoeoss/configserver:1.3.2"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - ../src/config:/config
    ports:
      - "8888:8888" 

  # eureka:   
    # image: "steeltoeoss/eurekaserver:1.4.4"
    # ports:
      # - "8761:8761"

