apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: fluentd
  name: fluentd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fluentd
    spec:
      containers:
      - image: fluentd
        name: fluentd
        ports:
        - containerPort: 24224
        - containerPort: 24224
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /fluentd/etc
          name: fluentd-claim0
      restartPolicy: Always
      volumes:
      - name: fluentd-claim0
        configMap:        
          name: fluentd-config
        #persistentVolumeClaim:
          #claimName: fluentd-claim0
status: {}
