apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: fluentd
  name: fluentd
spec:
  ports:
  - name: "24224"
    port: 24224
    targetPort: 24224
  - name: 24224-udp
    port: 24224
    protocol: UDP
    targetPort: 24224
  selector:
    io.kompose.service: fluentd
status:
  loadBalancer: {}
