apiVersion: v1
kind: Service
metadata:  
  labels:
    app: webtest
  name: webtest
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: webtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webtest
        version: v1
    spec:
      containers:
      - image: phongnhu/webtest:0.1
        name: webtest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80