apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: config-server
    spec:
      containers:
      - args:
        - --spring.profiles.active=native
        - --spring.cloud.config.server.native.searchLocations=/config
        image: steeltoeoss/configserver:1.3.2
        name: config-server
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
