version: '3.2'
services:
  mysql:
    container_name: kikkerauth_mysql
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      #MYSQL_SERVER_NAME: localhost
      MYSQL_ROOT_PASSWORD: auth
      MYSQL_DATABASE: kikkerauth
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - dbvol:/var/lib/mysql
volumes: 
  dbvol:
