version: '3.0'

services:  

  # config-server:
    # image: "steeltoeoss/configserver:1.3.2"
    # command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    # volumes:
      # - ./src/config:/config
    # ports:
      # - "8888:8888"

  #eureka:   
    #image: "steeltoeoss/eurekaserver:1.4.4"
    #ports:
      #- "8761:8761"
    #depends_on:
      #- config-server

  # elasticsearch:
    # build:
      # context: elasticsearch/
    # volumes:
      # - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    # ports:
      # - "9200:9200"
      # - "9300:9300"
    # environment:
      # ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    # networks:
      # - elk

  # logstash:
    # build:
      # context: logstash/
    # volumes:
      # - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      # - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    # ports:
      # - "8080:8080"
    # environment:
      # LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    # networks:
      # - elk
    # depends_on:
      # - elasticsearch

  # kibana:
    # build:
      # context: kibana/
    # volumes:
      # - ./kibana/config/:/usr/share/kibana/config:ro
    # ports:
      # - "5601:5601"
    # networks:
      # - elk
    # depends_on:
      # - elasticsearch

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kikker
      MYSQL_USER: user
      MYSQL_PASSWORD: 123

  # simpleservice:
    # image: simpleservice
    # build:
      # context: .
      # dockerfile: src/SimpleService_Docker/Dockerfile
    # #ports:
      # #- "5101:80"
    # #expose:
      # #- "5101"
    # # volumes:
      # # - appbuild:/app
      # # - ./src/SimpleService_Docker/Scripts:/app/Scripts
    # links:
      # - config-server
      # - mysql
      # #- eureka
    # depends_on:
      # - config-server
      # - mysql
      # #- eureka

  # simpleservice_kubernetes:
    # image: kikker-simpleservice-kubernetes
    # build:
      # context: .
      # dockerfile: src/SimpleService_Kubernetes/Dockerfile
    # links:
      # - config-server
      # - eureka
      # - mysql
    # depends_on:
      # - config-server
      # - eureka
      # - logstash
      # - mysql

#Kubernetes deployments
  # webapitest:
    # image: kikker_webapitest
    # build:
      # context: .
      # dockerfile: src/WebApiTest/Dockerfile 

  # webtest:
    # image: ${DOCKER_REGISTRY}webtest
    # build:
      # context: .
      # dockerfile: src/WebTest/Dockerfile

  #apigateway:
    #image: phongnhu/apigateway
    #build:
      #context: .
      #dockerfile: src/ApiGateway-Kubernetes/Dockerfile

# networks:
  # elk:
    # driver: bridge



  rating:
    image: phongnhu/rating:0.3
    build:
      context: .
      dockerfile: src/Rating/Dockerfile

