version: '3.0'

services:  

  config-server:
    image: "steeltoeoss/configserver:1.3.2"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - ./src/config:/config
    ports:
      - "8888:8888"

  #eureka:   
    #image: "steeltoeoss/eurekaserver:1.4.4"
    #ports:
      #- "8761:8761"
    #depends_on:
      #- config-server

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kikker
      MYSQL_USER: user
      MYSQL_PASSWORD: 123

  simpleservice-docker:
    image: kikker-simpleservice-docker
    build:
      context: .
      dockerfile: src/SimpleService_Docker/Dockerfile
    ports:
      - "5101:80"
    #expose:
      #- "5101"
    # volumes:
      # - appbuild:/app
      # - ./src/SimpleService_Docker/Scripts:/app/Scripts
    links:
      - config-server
      - mysql
      - eureka
    depends_on:
      - config-server
      - mysql
      - eureka

  # simpleservice_kubernetes:
    # image: kikker-simpleservice-kubernetes
    # build:
      # context: .
      # dockerfile: src/SimpleService_Kubernetes/Dockerfile
    # links:
      # - config-server
      # - eureka
      # - mysql
    # depends_on:
      # - config-server
      # - eureka
      # - logstash
      # - mysql

#Kubernetes deployments
  # webapitest:
    # image: kikker_webapitest
    # build:
      # context: .
      # dockerfile: src/WebApiTest/Dockerfile 

  # webtest:
    # image: ${DOCKER_REGISTRY}webtest
    # build:
      # context: .
      # dockerfile: src/WebTest/Dockerfile


  

