version: '3.2'
services:  
  simpleservice_docker:
    image: kikker_simpleservice2:${TAG:-latest}
    build:
      context: .
      dockerfile: src/SimpleService_Docker/Dockerfile
    ports:
      - "5101:80"
    volumes:
      - appbuild:/app
      - ./src/SimpleService_Docker/Scripts:/app/Scripts
    links:
      - config
      - eureka
      - mysql      
    #environment:
      #MYSQL_SERVER_NAME: ${MYSQL_SERVER_NAME}      
    depends_on:
      - config
      - eureka
      - logstash
      - mysql
  config:    
    image: "steeltoeoss/configserver:1.3.2"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/config
        target: /config
    ports:
      - "8888:8888"
  eureka:   
    image: "steeltoeoss/eurekaserver:1.4.4"
    ports:
      - "8761:8761"

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "8080:8080"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  mysql:
    container_name: kikker_mysql
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      #MYSQL_SERVER_NAME: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kikker
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - dbvol:/var/lib/mysql
networks:
  elk:
    driver: bridge
volumes:
  appbuild:
  dbvol:
