apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: logstash
        name: logstash
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: logstash-config-file-k
          mountPath: /usr/share/logstash/config/logstash.yml
        - name: logstash-pipeline-k
          mountPath: /usr/share/logstash/pipeline
      volumes:
       - name: logstash-config-file-k
         configMap:        
           name: logstash-config-file
       - name: logstash-pipeline-k
         configMap:         
           name: logstash-pipeline
      restartPolicy: Always
status: {}
