apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: simpleservice-docker
  name: simpleservice-docker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: simpleservice-docker
    spec:
      containers:
      - image: kikker-simpleservice
        name: simpleservice-docker
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
