apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: simpleservice
  name: simpleservice
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: simpleservice
    spec:
      containers:
      - image: infodation.azurecr.io/phongnhu/simpleservice:latest
        name: simpleservice
        resources: {}
      restartPolicy: Always
status: {}
