apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: simpleservice
  name: simpleservice
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 80
  selector:
    io.kompose.service: simpleservice
status:
  loadBalancer: {}
